spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql123456
    url: jdbc:mysql://134.175.6.159:3306/test?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8000